steps:
  # Build the container image from backend directory only
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/accorria-backend/accorria-backend', '.']
    dir: './backend'
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/accorria-backend/accorria-backend']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'accorria-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/accorria-backend/accorria-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'CLOUDBUILD=true,SECRET_KEY=your-secret-key-here,PORT=8000,REDIS_HOST=,REDIS_URL='
      - '--service-account'
      - '691352445702-compute@developer.gserviceaccount.com'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/accorria-backend/accorria-backend' 